### ISSUE TITLE
RCTView generated view config for validAttributes does not match native, missing: fsClass

### ISSUE THREAD

**Issue by umang-simform** [fullstorydev/fullstory-react-native#7]
I am trying to integrate this into our react-native app.
I went through this article: 
https://help.fullstory.com/hc/en-us/articles/360042772333-Getting-Started-with-iOS-Recording
Seriously there is zero documentation for how to use it on react-native 👎 .
I added use_frameworks! in my podfiles so I got errors for other dependencies. and I solved all of those errors,
Then I added at the bottom of podfile: 
pod 'FullStory', :http => 'https://ios-releases.fullstory.com/fullstory-1.3.0.tar.gz'
I run npm install again and then installed pods again but this error does not go away.

`console.error: "RCTView generated view config for validAttributes does not match native, missing: fsClass"`

Versions:
React-native : 0.61.3
@fullstory/react-native: "0.9.2"

**Comment by JoshMiers-FS** [comment]
Hey there!

Thanks for reaching out and filing an issue with us here on Github. Our react native plugin is currently in private beta which is why you may find the documentation a bit hard to follow. If you’re interested in gaining access to the private beta, please email mobile-support@fullstory.com and we’ll follow up with next steps.

While we wish we could grant everyone access to the beta program, please bear in mind that we’re evaluating each request on a case-by-case basis and admission into the beta is not guaranteed. Once we’re out of private beta and access to our react-native plugin is more widely available, we will update our documentation with steps on how to integrate it properly into your project.

Sorry for any confusion this has caused and thank you for your patience while we work to make this plugin great for the entire community.

**Comment by itsthisjustin** [comment]
For what it's worth @JoshMiers-FS, you should really update the readme here to reflect that. Wasted a whole day on this losing precious time.

**Comment by JoshMiers-FS** [comment]
I've got a PR to make the change to the README. Sorry for the confusion!

**Comment by mattjbrill** [comment]
I encountered the same issue. Seems to be related to the Metro cache. I gave it a quick 
```
npm start -- --reset-cache
```
and was back on my way.

This happened on both an existing project, and a fresh squeezed (npx react-native init) one.

**Comment by benevbright** [comment]
`rm -rf ios/build` worked for me.

**Comment by simistern** [comment]
I am still seeing this and neither of the above options work for me, 
We are on `"@fullstory/react-native": "1.0.1",`

**Comment by jwise** [comment]
Hi @simistern -- can you send our support team some mail?  We're not really set up to do support via GitHub, but if you mail mobile-support@fullstory.com , we'll get you squared away.
